### ISSUE TITLE
Retrieve list of available channels

### ISSUE THREAD

**Issue by HosseinArabbeigi** [LeoIsasmendi/exampleHikvisionSDKPlayer#3]
Hello @LeoIsasmendi 
thanks for amazing example

I need to receive list of available cameras and connect to them, can you please tell how to do that?
Its not documented, in your sample we are connecting to start channel and we haven't any information about other channels.

Thanks.

**Comment by LeoIsasmendi** [comment]
Hi @HosseinArabbeigi you can use SADP Tool from the Hikvision page (https://www.hikvision.com/en/support/tools/destop-tools/sadp-for-windows/) it's available also for Mac.
This tool will show you a list of devices available in your subnet.
You can also visit the Hikvision official site for documentation and tools.
Kind Regards!

**Comment by HosseinArabbeigi** [comment]
Thanks @LeoIsasmendi, but i need to do it in android java code.
Also i did search in hikvision sdk documentation, but there wasn't any thing about retrieve list of available cameras.

**Comment by LeoIsasmendi** [comment]
Ok, no problem @HosseinArabbeigi, as soon as I can find SADP library for Android I will be uploading an example.
Regards!
