### ISSUE TITLE
Where to find the latest Android SDK?

### ISSUE THREAD

**Issue by Mokyyds** [LeoIsasmendi/exampleHikvisionSDKPlayer#4]
Hi, thank you very much for your code. 
I want to know where to download the latest Android SDK for Hikvision cameras.
Because I think the official website can only be downloaded to for the Windows or Linux, where does the Jar file in your code come from? Thank you!

**Comment by LeoIsasmendi** [comment]
Hi @Peachou, you can request the latest Android SDK sending a mail to support@hikvision.com, they will provide a link where you can download the files.
