### ISSUE TITLE
Can I use this as an example to see livestream of hikvision camera over internet on my custom app

### ISSUE THREAD

**Issue by linux-devil** [LeoIsasmendi/exampleHikvisionSDKPlayer#5]
I am trying to see realtime live stream of hikvision camera on my own custom android application . Is it possible to achieve it ?

**Comment by LeoIsasmendi** [comment]
Hi!
I'm not sure about that. But if you have a camera with public IP and no filtered ports by a router or firewall, I think it can be possible. I never try that way. Please let me know if you can achieve that. Regards!
